
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("dtb_product/new", "Create dtb_product")) ?>
</div>

<?php echo $this->tag->form(array("dtb_product/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search dtb_product</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="product_id">Product</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("product_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="user_Id">User Of Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("user_Id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="project_name">Project Of Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("project_name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="product_name">Product Of Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("product_name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="price">Price</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("price", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="product_img">Product Of Img</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("product_img", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="exist_num">Exist Of Num</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("exist_num", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
