
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("dtb_product/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("dtb_product", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<div align="center">
    <h1>Edit dtb_product</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="user_Id">User Of Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("user_Id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="project_name">Project Of Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("project_name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="product_name">Product Of Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("product_name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="price">Price</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("price", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="product_img">Product Of Img</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("product_img", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="exist_num">Exist Of Num</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("exist_num", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td><?php echo $this->tag->hiddenField("id") ?></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
